spring.application.name=financialcontrol

spring.datasource.url=jdbc:postgresql://localhost:5432/controlefinanceiro_lab
spring.datasource.username=postgres
spring.datasource.password=Vanda1107.

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=umSegredoQualquerParaLabDev12345
jwt.expiracao-ms=86400000

admin.email=admin@lab.com
admin.senha=admin123

cors.origins=http://127.0.0.1:5500